vspeed = -0.1
credit_mode = true;
text = "Project Leader:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Concept Art & Character Design:" + "\n"
+ "Putri Yoni Jesica" + "\n"
+ "\n" + "\n"
+ "Programming:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Sprite Artist:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Promotional Designer:" + "\n"
+ "Padumuttaro Sattasaro" + "\n"
+ "\n" + "\n"
+ "Guru Pembimbing:" + "\n"
+ "Fransisca Intan Megasari" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Special Thanks to:" + "\n"
+ "Sacca Kirana" + "\n"
+ "as a Loyal Tester" + "\n"
+ "\n" + "\n"
+ "Marvel Eugene Mackenzie" + "\n"
+ "as a Loyal Tester" + "\n"
+ "\n" + "\n"
+ "Gracia Hawila" + "\n"
+ "as the Artwork Artist" + "\n"
+ "\n" + "\n"
+ "@shie_angeli" + "\n"
+ "for Naya fanart" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Music by: https://www.steven-obrien.net/" + "\n"
+ "\n" + "\n"
+ "Allure" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "Refined" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "You Inspire Me" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "Foreboding Thoughts" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "Culmination" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "I Want To Go" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "Gear Head" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "Epic Powerful Electronic" + "\n"
+ "Steven O'Brien" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Notes from Timothy:" + "\n"
+ "Ini merupakan game sederhana yang kami buat untuk menyelesaikan tugas ujian praktek kami. Mudah-mudahan dengan adanya game ini bisa membuat adik-adik kelas kita jauh lebih mudah mengerti tentang konsep himpunan. Soalnya matematika itu seru lohh :)" + "\n"
+ "\n" + "\n"
+ "Kalau kamu menemukan bug tolong laporkan secepatnya dengan DM instagram saya: @thio.timoo" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Thanks for playing :)" + "\n"
