vspeed = -0.1
credit_mode = true;
text = "Project Leader:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Concept Art:" + "\n"
+ "Putri Yoni Jesica" + "\n"
+ "\n" + "\n"
+ "Programming:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Sprite Artist:" + "\n"
+ "Vincent Timothy Kurniawan" + "\n"
+ "\n" + "\n"
+ "Promotional Designer:" + "\n"
+ "Padumuttaro Sattasaro" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Special Thanks to:" + "\n"
+ "Sacca Kirana" + "\n"
+ "as a Loyal Tester" + "\n"
+ "\n" + "\n"
+ "Marvel Eugene Mackenzie" + "\n"
+ "as a Loyal Tester" + "\n"
+ "\n" + "\n"
+ "@shie_angeli" + "\n"
+ "for Naya fanart" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Musics used:" + "\n"
+ "\n" + "\n"
+ "Mata Ke Hati (Instrumental)" + "\n"
+ "HIVI!" + "\n"
+ "\n" + "\n"
+ "Take On Me" + "\n"
+ "a-ha" + "\n"
+ "\n" + "\n"
+ "Mind Game" + "\n"
+ "Mojiken Studio" + "\n"
+ "\n" + "\n"
+ "LilaS (Instrumental)" + "\n"
+ "Hiroyuki Sawano" + "\n"
+ "\n" + "\n"
+ "Jadi Yang Kuinginkan" + "\n"
+ "VIERRA" + "\n"
+ "\n" + "\n"
+ "Avid (Instrumental)" + "\n"
+ "Hiroyuki Sawano" + "\n"
+ "\n" + "\n"
+ "Voice? (Koe?)" + "\n"
+ "Hatena" + "\n"
+ "\n" + "\n"
+ "As It Was" + "\n"
+ "Harry Styles" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Notes from Timothy:" + "\n"
+ "Ini merupakan game sederhana yang kami buat untuk menyelesaikan tugas ujian praktek kami. Mudah-mudahan dengan adanya game ini bisa membuat adik-adik kelas kita jauh lebih mudah mengerti tentang konsep himpunan. Soalnya matematika itu seru lohh :)" + "\n"
+ "\n" + "\n"
+ "Kalau kamu menemukan bug tolong laporkan secepatnya dengan DM instagram saya: @vtimotyh_" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "\n" + "\n"
+ "Thanks for playing :)" + "\n"
