draw_set_color(image_blend);
draw_set_alpha(image_alpha)
draw_set_valign(fa_middle)
draw_set_halign(fa_center)
draw_text_outline(x,y,str)
draw_set_valign(fa_top)
draw_set_halign(fa_left)
draw_set_color(c_white)
draw_set_alpha(1)